### ISSUE TITLE
add a static header which says "Buttons"

### ISSUE THREAD

**Issue by kushagrarora17** [kushagrarora17/animated-buttons-hacktoberfest#9]

**Comment by Abhishek-Mittall** [comment]
I can do this

**Comment by kushagrarora17** [comment]
@Abhishek-Mittall When will you be able to complete?

**Comment by Abhishek-Mittall** [comment]
I am already working on it . Please tell me what type of styling you want in it

**Comment by kushagrarora17** [comment]
Doesn't matter much.

Regards,
Kushagr
+91-9643711706

**Comment by Abhishek-Mittall** [comment]
I have send you pr. Have a look at it.

**Comment by kushagrarora17** [comment]
> I have send you pr. Have a look at it.

I found some issues in it. Can you please correct them?

**Comment by Abhishek-Mittall** [comment]
yes tell me

**Comment by Abhishek-Mittall** [comment]
I am sending you another pull request

**Comment by kushagrarora17** [comment]
merged. thanks.
